### PR TITLE
installer: uninstall old Solid version before installation

### LINKED ISSUE #12: bug: sometimes old version of Solid must be uninstalled before installing new version
When upgrading from version 0.21 to v1.0 you must first uninstall Solid before installing v1.0 otherwise you may get a crash about a Keyman DLL mismatch.

Our installer should be smart enough to uninstall solid before installing the new one.

### PR DESCRIPTION
**Pull request by megahirt**
Fixes #12

This updates the installer script to check for a prior version of Solid and uninstall that before proceeding with the installation.  This fixes some bugs related to upgraded dependencies that are not cleaned up on new installs.

The uninstall script / detection was taken from https://stackoverflow.com/a/2099805

### CODE REVIEW

**Comment by josephmyers** [comment]
I think we should enable the GHA steps to create/sign the installer even for branches. It's a little inconvenient to have to pull this branch and build the installer locally, and having the installer as an artifact should be useful for future cases, as well. Thoughts?

**Comment by megahirt** [comment]
> I think we should enable the GHA steps to create/sign the installer even for branches. It's a little inconvenient to have to pull this branch and build the installer locally, and having the installer as an artifact should be useful for future cases, as well. Thoughts?

@josephmyers so the idea is that creating/signing an installer is only for when we decide to release at a certain commit via a tag.  Creating installers should be left up to CI almost exclusively.  The only time a dev should make an installer locally would be if they are making changes to the installer itself.

Theoretically a tag can be created anywhere, including on a branch.  In practice, the tag vX.X.X should be done on a commit on `main`, not on a feature branch.  This same action also produces a draft release, so it really is a publish action.

If for some reason we want to produce an installer to give to someone without publishing, we create a tagged version and then leave the release as draft, and then send them a link to the installer artifact.

**Comment by josephmyers** [comment]
I'm fine with that. At the very least I'm emphasizing that I don't know how to test this branch without getting iscc working on my machine and building the installer locally, which I won't have time for until tomorrow. Maybe I'm missing something obvious?

**Comment by megahirt** [comment]
> I'm fine with that. At the very least I'm emphasizing that I don't know how to test this branch without getting iscc working on my machine and building the installer locally, which I won't have time for until tomorrow. Maybe I'm missing something obvious?

Ah yes, I see your point.  I should have also said that I tested this locally with my changes and went through installing / uninstalling a number of times to get this working.

For CI, we can make a release with a tag and then test the installer out that way.

**Pull request merged**
